In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [7]:
price = np.array([1096.95, 384, 28593.43])
c = [30.1]


In [8]:
price

array([ 1096.95,   384.  , 28593.43])

In [9]:
price *c

array([ 33018.195,  11558.4  , 860662.243])

In [11]:
grades = np.array([85,70,82])

In [12]:
weight = np.array([0.3,0.4, 0.3])

In [13]:
g= grades*weight


In [14]:
g

array([25.5, 28. , 24.6])

In [15]:
g.sum()

78.1

In [16]:
#另一個方法，可以用numpy裡面的內稽
np.dot(grades, weight)

78.1

In [17]:
grade=np.array([[85,70,84],[75,67,78],[57,37,78],[96,97,76]])
#假設是要算四位同學的三次月考成績，百分比分別是上面的weight(0.3, 0.4, 0.3)

In [18]:
np.dot(grade,weight)
#為什麼可以直接內積

array([78.7, 72.7, 55.3, 90.4])

In [19]:
L=np.array([3, 5, 6, 4])

In [20]:
L*4
#我們可以把一個np.array看成一整個元素，只要乘就會整個中括號一起動。所以算內積可以直接dot

array([12, 20, 24, 16])

In [21]:
xy= [[x,y]for x in range(10) for y in range(5)]

In [22]:
xy

[[0, 0],
 [0, 1],
 [0, 2],
 [0, 3],
 [0, 4],
 [1, 0],
 [1, 1],
 [1, 2],
 [1, 3],
 [1, 4],
 [2, 0],
 [2, 1],
 [2, 2],
 [2, 3],
 [2, 4],
 [3, 0],
 [3, 1],
 [3, 2],
 [3, 3],
 [3, 4],
 [4, 0],
 [4, 1],
 [4, 2],
 [4, 3],
 [4, 4],
 [5, 0],
 [5, 1],
 [5, 2],
 [5, 3],
 [5, 4],
 [6, 0],
 [6, 1],
 [6, 2],
 [6, 3],
 [6, 4],
 [7, 0],
 [7, 1],
 [7, 2],
 [7, 3],
 [7, 4],
 [8, 0],
 [8, 1],
 [8, 2],
 [8, 3],
 [8, 4],
 [9, 0],
 [9, 1],
 [9, 2],
 [9, 3],
 [9, 4]]

In [23]:
xy = np.array(xy)
xy

array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [0, 4],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4],
       [3, 0],
       [3, 1],
       [3, 2],
       [3, 3],
       [3, 4],
       [4, 0],
       [4, 1],
       [4, 2],
       [4, 3],
       [4, 4],
       [5, 0],
       [5, 1],
       [5, 2],
       [5, 3],
       [5, 4],
       [6, 0],
       [6, 1],
       [6, 2],
       [6, 3],
       [6, 4],
       [7, 0],
       [7, 1],
       [7, 2],
       [7, 3],
       [7, 4],
       [8, 0],
       [8, 1],
       [8, 2],
       [8, 3],
       [8, 4],
       [9, 0],
       [9, 1],
       [9, 2],
       [9, 3],
       [9, 4]])